#!/usr/bin/env bash
# This is a pre-commit hook that validates code formatting.
#
# Install this by running the script with an argument of "install",
# which installs a symlink to .git/hooks/precommit:
# $ ln -s ../../hooks/pre-commit .git/hooks/pre-commit

root="$(git rev-parse --show-toplevel 2>/dev/null)"

set -e

# Some sanity checking.
hash cargo
[[ -n "$root" ]]

# Installation.
if [[ "$1" == "install" ]]; then
    hook="$root"/.git/hooks/pre-commit
    if [[ ! -e "$hook" ]]; then
        ln -s ../../pre-commit "$hook"
        echo "Installed git pre-commit hook at $hook"
    else
        echo "Hook already installed"
    fi
    exit
fi

save_merge_files() {
    # MERGE_[HEAD|MODE|MSG]
    for f in "$root"/.git/MERGE_*; do
	if [[ -e "$f" ]]; then
            t=$(basename $f)
            cp -f "$f" "$t"
	fi
    done
}

restore_merge_files() {
    for f in MERGE_*; do
	if [[ -e "$f" ]]; then
            t=$(basename $f)
	    if [[ -e "${root}/.git/${t}" ]]; then
		echo "Failed to restore ${t}. File already exists"
		exit 1
	    fi
            mv -f "$f" "${root}/.git/${t}"
	fi
    done
}

# Check formatting.
stashfile=$(mktemp .pre-commit.stashXXXXXX)
trap 'set +e;git stash pop -q; rm -f "$stashfile"; restore_merge_files' EXIT
save_merge_files
git stash push -k -u -q -m "pre-commit stash"
if ! errors=($(cargo fmt -- --check -l)); then
    echo "Formatting errors found."
    echo "Run \`cargo fmt\` to fix the following files:"
    for err in "${errors[@]}"; do
        echo "  $err"
    done
    exit 1
fi

error() {
   echo "-----------------------"
   echo "$@"
   exit 1
}

cargo build --benches --features "enable-benches" || error "Benchmarks compilation errors"

cargo clippy --tests -- -D warnings || error "Clippy errors"

cargo clippy --tests --features shuttle -- -D warnings || error "Clippy concurrency tests errors"

cargo test || error "Test failures"

cargo test --features shuttle || error "Concurrency test failures"
