- name: Setup IPA Helper
  hosts: all
  tasks:
    - name: Store HOME directory
      debug:
        var: ansible_env.HOME

    - name: Check if rust toolchain is installed
      command: rustup --version
      register: rustup_installed
      failed_when: false
      changed_when: false

    - name: Install Rustup
      shell: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"
      args:
        executable: /bin/bash
      when: rustup_installed.rc != 0

    - name: Update Rust to 1.80
      command: rustup update 1.80.0

    - name: Set default to 1.80
      command: rustup default 1.80.0

    - name: Check if Git is installed
      command: git --version
      register: git_installed
      failed_when: false
      changed_when: false

    - name: Install GCC
      yum:
        name: gcc
        state: latest
      become: yes

    - name: Install Git
      yum:
        name: git
        state: latest
      become: yes
      when: git_installed.rc != 0

    - name: Clone repository if it doesn't exist
      git:
        repo: 'https://github.com/private-attribution/ipa.git'
        dest: '{{ ansible_env.HOME }}/ipa'
        update: no
        version: "{{ commit_hash }}"

    - name: Build IPA helper
      shell:
        cmd: "cargo build --bin helper --features='web-app real-world-infra compact-gate multi-threading disable-metrics' --no-default-features --release"
        chdir: "{{ ansible_env.HOME }}/ipa"

    - name: Grant CAP_NET_BIND_SERVICE capability to helper binary
      command: 'setcap cap_net_bind_service=+ep {{ ansible_env.HOME }}/ipa/target/release/helper'
      become: yes
