use crate::{
    error::Error,
    ff::Fp61BitPrime,
    helpers::{Direction, TotalRecords},
    protocol::{
        context::{
            dzkp_field::{UVTupleBlock, BLOCK_SIZE},
            Context,
        },
        ipa_prf::malicious_security::prover::{LargeProofGenerator, SmallProofGenerator},
        RecordId,
    },
};

/// This a `ProofBatch` generated by a prover.
pub struct ProofBatch {
    pub first_proof: [Fp61BitPrime; LargeProofGenerator::PROOF_LENGTH],
    pub proofs: Vec<[Fp61BitPrime; SmallProofGenerator::PROOF_LENGTH]>,
}

impl FromIterator<Fp61BitPrime> for ProofBatch {
    fn from_iter<T: IntoIterator<Item = Fp61BitPrime>>(iter: T) -> Self {
        let mut iterator = iter.into_iter();
        // consume the first P elements
        let first_proof = iterator
            .by_ref()
            .take(LargeProofGenerator::PROOF_LENGTH)
            .collect::<[Fp61BitPrime; LargeProofGenerator::PROOF_LENGTH]>();
        // consume the rest
        let proofs = iterator.collect::<Vec<[Fp61BitPrime; SmallProofGenerator::PROOF_LENGTH]>>();
        ProofBatch {
            first_proof,
            proofs,
        }
    }
}

impl ProofBatch {
    /// This function returns the length in field elements.
    pub fn len(&self) -> usize {
        self.proofs.len() * SmallProofGenerator::PROOF_LENGTH + LargeProofGenerator::PROOF_LENGTH
    }

    /// This function returns an iterator over the field elements of all proofs.
    fn iter(&self) -> impl Iterator<Item = &Fp61BitPrime> {
        self.first_proof
            .iter()
            .chain(self.proofs.iter().flat_map(|x| x.iter()))
    }

    /// This function sends a `Proof` to the party on the left
    pub async fn send_to_left<C>(&self, ctx: &C) -> Result<(), Error>
    where
        C: Context,
    {
        // set up context for the communication over the network
        let communication_ctx = ctx.set_total_records(TotalRecords::specified(self.len())?);

        // set up channel
        let send_channel_left =
            &communication_ctx.send_channel::<Fp61BitPrime>(ctx.role().peer(Direction::Left));

        // send to left
        // we send the proof batch via sending the individual field elements
        communication_ctx
            .parallel_join(
                self.iter().enumerate().map(|(i, x)| async move {
                    send_channel_left.send(RecordId::from(i), x).await
                }),
            )
            .await?;
        Ok(())
    }

    /// This function receives a `Proof` from the party on the right.
    pub async fn receive_from_right<C>(ctx: &C, length: usize) -> Result<Self, Error>
    where
        C: Context,
    {
        // set up context
        let communication_ctx = ctx.set_total_records(TotalRecords::specified(length)?);

        // set up channel
        let receive_channel_right =
            &communication_ctx.recv_channel::<Fp61BitPrime>(ctx.role().peer(Direction::Right));

        // receive from the right
        Ok(ctx
            .parallel_join(
                (0..length)
                    .map(|i| async move { receive_channel_right.receive(RecordId::from(i)).await }),
            )
            .await?
            .into_iter()
            .collect())
    }

    /// This is a helper function that allows to split a `UVTupleInputs`
    /// which consists of arrays of size `BLOCK_SIZE`
    /// into an iterator over arrays of size `LargeProofGenerator::RECURSION_FACTOR`.
    ///
    /// ## Panic
    /// Panics when `unwrap` panics, i.e. `try_from` fails to convert a slice to an array.
    pub fn polynomials_from_inputs<I>(
        inputs: I,
    ) -> impl Iterator<
        Item = (
            [Fp61BitPrime; LargeProofGenerator::RECURSION_FACTOR],
            [Fp61BitPrime; LargeProofGenerator::RECURSION_FACTOR],
        ),
    > + Clone
    where
        I: Iterator<Item = UVTupleBlock<Fp61BitPrime>> + Clone,
    {
        assert_eq!(BLOCK_SIZE % LargeProofGenerator::RECURSION_FACTOR, 0);
        inputs.flat_map(|(u_block, v_block)| {
            (0usize..(BLOCK_SIZE / LargeProofGenerator::RECURSION_FACTOR)).map(move |i| {
                (
                    <[Fp61BitPrime; LargeProofGenerator::RECURSION_FACTOR]>::try_from(
                        &u_block[i * LargeProofGenerator::RECURSION_FACTOR
                            ..(i + 1) * LargeProofGenerator::RECURSION_FACTOR],
                    )
                    .unwrap(),
                    <[Fp61BitPrime; LargeProofGenerator::RECURSION_FACTOR]>::try_from(
                        &v_block[i * LargeProofGenerator::RECURSION_FACTOR
                            ..(i + 1) * LargeProofGenerator::RECURSION_FACTOR],
                    )
                    .unwrap(),
                )
            })
        })
    }
}

#[cfg(all(test, unit_test))]
mod test {
    use rand::{thread_rng, Rng};

    use crate::{
        ff::{Fp61BitPrime, U128Conversions},
        protocol::{
            context::dzkp_field::BLOCK_SIZE,
            ipa_prf::validation_protocol::validation::{test::simple_proof_check, BatchToVerify},
        },
        secret_sharing::{replicated::ReplicatedSecretSharing, SharedValue},
        test_executor::run,
        test_fixture::{Runner, TestWorld},
    };

    impl Default for Fp61BitPrime {
        fn default() -> Self {
            Fp61BitPrime::ZERO
        }
    }

    #[test]
    fn generate_verifier_batch() {
        run(|| async move {
            let world = TestWorld::default();

            let mut rng = thread_rng();

            // each helper samples a random value h
            // which is later used to generate distinct values across helpers
            let h = Fp61BitPrime::truncate_from(rng.gen_range(0u128..100));

            let result = world
                .semi_honest(h, |ctx, h| async move {
                    let h = Fp61BitPrime::truncate_from(h.left().as_u128() % 100);
                    // generate blocks of UV values
                    // generate u values as (1h,2h,3h,....,10h*BlockSize) split into Blocksize chunks
                    // where BlockSize = 32
                    // v values are identical to u
                    let uv_tuple_vec = (0usize..100)
                        .map(|i| {
                            (
                                (BLOCK_SIZE * i..BLOCK_SIZE * (i + 1))
                                    .map(|j| {
                                        Fp61BitPrime::truncate_from(u128::try_from(j).unwrap()) * h
                                    })
                                    .collect::<[Fp61BitPrime; BLOCK_SIZE]>(),
                                (BLOCK_SIZE * i..BLOCK_SIZE * (i + 1))
                                    .map(|j| {
                                        Fp61BitPrime::truncate_from(u128::try_from(j).unwrap()) * h
                                    })
                                    .collect::<[Fp61BitPrime; BLOCK_SIZE]>(),
                            )
                        })
                        .collect::<Vec<_>>();

                    // generate and output VerifierBatch together with h value
                    (
                        h,
                        BatchToVerify::generate_batch_to_verify(ctx, uv_tuple_vec.into_iter())
                            .await,
                    )
                })
                .await;

            // proof from first party
            simple_proof_check(result[0].0, &result[2].1, &result[1].1);

            // proof from second party
            simple_proof_check(result[1].0, &result[0].1, &result[2].1);

            // proof from third party
            simple_proof_check(result[2].0, &result[1].1, &result[0].1);
        });
    }
}
