#!/usr/bin/env bash
# shamelessly stolen from https://github.com/rustls/rustls/blob/c296594db33c7d50ab642ab48f8302e6a88dcebf/admin/coverage

set -e

source <(cargo llvm-cov show-env --export-prefix)
cargo llvm-cov clean --workspace

cargo build --all-targets

# Need to be kept in sync manually with tests we run inside check.yml.
cargo test --features "cli test-fixture relaxed-dp"

# Provide code coverage stats for ipa-metrics crate with partitions enabled
cargo test -p ipa-metrics --features "partitions"

for gate in "compact-gate" "descriptive-gate"; do
  cargo test --no-default-features --features "cli web-app real-world-infra test-fixture $gate"
done

cargo test --bench criterion_arithmetic --no-default-features --features "enable-benches compact-gate"

# compact gate + in-memory-infra
cargo test --features "compact-gate"

cargo llvm-cov report "$@"
